### ISSUE TITLE
weekendDays sometimes incorrect

### ISSUE THREAD

**Issue by carpeliam** [jmeas/moment-business#51]
The following code returns an incorrect value for the number of weekend days:

```javascript
const start = moment.utc("2016-07-25T13:43:00.000+00:00");
const end = moment.utc("2016-08-22T11:28:00.000+00:00");
business.weekendDays(start, end); // returns 7, expected 8
```

Is this right?

**Comment by jamesplease** [comment]
Hi @carpeliam , thanks for the issue! Looking at a calendar, I agree with you that this should be 8. I'll take a look.

**Comment by carpeliam** [comment]
@jmeas the calculation we used was as follows, not sure if this helps:
```javascript
let numOfWeekends = moment(start).startOf('day').diff(moment(end).startOf('day'), 'weeks');
if (started.day() > accepted.day()) {
  numOfWeekends += 1;
}
const numOfWeekendDays = 2 * numOfWeekends;
```

of course this doesn't work if the number of weekend days should be odd...

**Comment by jamesplease** [comment]
Thanks @carpeliam !

That calculation seems smart, and quick. In fact, I could probably just go ahead and drop it in to this library and that'd be great. Before I do, though, I want to make sure that there's not a deeper issue here, since the weekend days method builds on top of the `weekDays()` calculation.

My prediction is that I may have made an assumption related to the inclusive start/exclusive start of the weekday interval that is returned. If that's the case, then maybe it only applies to some specific calculations but not all. I'll be looking into this more tonight.

Sorry that you ran into this issue – but thanks for filing the report!

**Comment by jamesplease** [comment]
@carpeliam , I dug into this now because I was just too curious.

I don't think this is a bug with the algorithm used here, which is good. Instead, I think this unexpected result is correct, given your input and the current way this lib is set up, which isn't to say that there are no improvements to be made.

The tl;dr is that this library requires that you work with only _dates_, and never _times_. This requirement could definitely be documented better, though.

In this situation, your inclusion of times (everything past the T) means that one of those days isn't fully being taken into account when moment is doing its diff, which breaks an assumption this library is making. This results in the off-by-1 error you're seeing.

To compare this with the algorithm that you provided, this library does not ever do `startOf('day')`. Perhaps it should. The other alternative is that I just update the docs to say something to the effect of: "always be sure to strip out the times from your date objects".

Anyway, if you `.startOf()` all of your dates before passing them into moment-business, then this library should always work as expected.

In code:

```js
const start = moment.utc("2016-07-25");
const end = moment.utc("2016-08-22");
business.weekendDays(start, end); // returns 8, as expected
```

or,

```js
const start = moment.utc("2016-07-25T13:43:00.000+00:00").startOf('day');
const end = moment.utc("2016-08-22T11:28:00.000+00:00").startOf('day');
business.weekendDays(start, end); // returns 8, as expected
```

What do you think would be best?

**Comment by jamesplease** [comment]
@carpeliam for now, I updated the docs so that future devs don't run into the same issue. I'm open to changing the code if you think it would make the library behave more predictably. Let me know. And thanks again for opening the issue!
